### ISSUE TITLE
Type-only imports are converted to regular ones on sort

### ISSUE THREAD

**Issue by FredyC** [daidodo/tsimportsorter#14]
**Describe the bug**
TS 3.8 introduced the new feature of [Type-Only imports](https://devblogs.microsoft.com/typescript/announcing-typescript-3-8/#type-only-imports-exports) which is really for optimizing.

Unfortunately, the extension is not able to preserve it and the keyword is removed during the sort.

**To Reproduce**
```ts
import type { Client } from 'urql'
```

**Expected behavior**
Import should keep `type` keyword.

**Actual behavior**
```ts
import { Client } from 'urql'
```

**OS (please complete the following information):**
 - OS: Windows
 - Version: 10

**VS Code (please complete the following information):**
 - Version: 1.45.0

I believe the fix should be fairly trivial and I am able to work on the PR.

**Comment by daidodo** [comment]
Feature has been release from **v2.1.4**.

@FredyC, thanks very much for the contribution!

**Comment by FredyC** [comment]
Working nicely. I thank you for your quick response and fix.
