### ISSUE TITLE
Newline at end of file gets removed

### ISSUE THREAD

**Issue by JordanLongstaff** [daidodo/tsimportsorter#16]
Hi, I've got a file that has a bunch of exports at the end, followed by a blank line. Having a blank line at the end of a file is good practice and is something that the linter at my work requires. However, when I save the file, the blank line at the end disappears. It doesn't happen to most files, but it happens to this one because of the exports at the end.

There might already be a way to fix this on my end, but I don't know what it is.

**Comment by daidodo** [comment]
@JordanLongstaff, thanks for the feedback!

This extension keeps final newline by default. The ways to change it are:
* package.json
    ```json
    {
      "importSorter": {
        "insertFinalNewline": true
      }
    }
    ```
* import-sorter.json
    ```json
    {
      "insertFinalNewline": true
    }
    ```

If you still have problems with the above config, I need to know:
* Any other formatter extensions you are using,
* Your configuration in *package.json* or *import-sorter.json*.

**Comment by JordanLongstaff** [comment]
Worked perfectly. Thanks!
