### ISSUE TITLE
No blank line between .css / .scss and other imports

### ISSUE THREAD

**Issue by calvindio** [daidodo/tsimportsorter#17]
I just want a simple Boolean to say "no blank lines to all imports be it groups or subgroups"

**Describe alternatives you've considered**
Or a step by step instruction on readme to implement "no blank line separator" using the subgroup methods so it is easier for newbies to search "blank lines" on the wiki / readme and follow them. Right now, the instructions is quite vague and requires the user to understand regex rules.

**Additional context**
I tried this setting but the result is not what i intended:
```json
	"tsImportSorter.configuration.groupRules": [
		[
			"^react(-dom)?$",
			"^@angular/",
			"^vue$",
			{},
			"^[@]",
			"^[.]",
			{
				"flag": "scripts",
				"regex": ".scss$"
			}
		]
	],
```
the result
```js
//intended
import './App.scss'
import { SignPage } from '../SignPage/SignPage'

. . . my codes

//what happened
import './App.scss'

import { SignPage } from '../SignPage/SignPage'

. . . my codes
```

**Comment by daidodo** [comment]
@calvindio, Thanks for your feedback!

I need to understand your requirement a bit more.
Are you talking about only `.css / .scss` imports or any script imports? Ex.
```js
import 'any/script';

import 'App.scss'
import { SignPage } from '../SignPage/SignPage'
```
or 
```js
import 'any/script';
import 'App.scss'
import { SignPage } from '../SignPage/SignPage'
```

Either way, you can achieve it via grouping rules, e.g. in the 1st case:
```json
{
  "groupRules": [
    {
      "flag": "all",
      "subGroups": [
        { "flag": "scripts", "regex": ".scss$"},    // Remove "regex" field to apply to all script imports (2nd case)
        "^react(-dom)?$",
        "^@angular/",
        "^vue$",
        {},
        "^[@]",
        "^[.]"
      ]
    }
  ]
}
```

However, I have to admit that the solution is far from straightforward. If your requirement is case 2, I can add an `EmptyLinesBetweenGroups`.

**Comment by daidodo** [comment]
@calvindio I've added EmptyLinesBetweenGroups anyway.

Will close the issue.

**Comment by calvindio** [comment]
Thank you!
