### ISSUE TITLE
".." path converted to "../"

### ISSUE THREAD

**Issue by spoissant** [daidodo/tsimportsorter#18]
**Describe the bug**
Import like this:
`import BlurredBackground from '..';`
Get transformed to this:
`import BlurredBackground from '../';`

But we are using eslint with import/no-useless-path-segments (https://github.com/benmosher/eslint-plugin-import/blob/master/docs/rules/no-useless-path-segments.md) so every time I have a similar import and format them I have to manually remove the extra `/` to please eslint.

Maybe this could be an additional setting?

**To Reproduce**
1. Add an import like `import BlurredBackground from '..';`
2. Run the "Sort Imports/Export" command

**Expected behavior**
Import remains unchanged 
`import BlurredBackground from '..';`

**Actual behavior**
Import path is updated with a trailing `/` 
`import BlurredBackground from '../';`

**OS (please complete the following information):**
 - OS: Ubuntu
 - Version: 20.04

**VS Code (please complete the following information):**
 - Version: 1.46.1

**Installed VS Code extensions**
```
alexkrechik.cucumberautocomplete
CoenraadS.bracket-pair-colorizer
dbaeumer.vscode-eslint
dozerg.tsimportsorter
eamodio.gitlens
EditorConfig.EditorConfig
esbenp.prettier-vscode
jpoissonnier.vscode-styled-components
karunamurti.haml
mikestead.dotenv
Orta.vscode-jest
rebornix.ruby
skyran.js-jsx-snippets
vscode-icons-team.vscode-icons
wingrunr21.vscode-ruby

```

**Comment by daidodo** [comment]
@spoissant, thanks for the feedback!

Actually, that is intentional as a result of [this discussion](https://github.com/SoominHan/import-sorter/issues/48).
Tell me if you have further questions!

**Comment by daidodo** [comment]
@spoissant, will resolve the issue.

Feel free to reopen it if you have more questions.

**Comment by spoissant** [comment]
Hi @daidodo ! Thanks for your quick response. 

I read through the discussion you linked and I understand your point. It would be nice if the extension would only add the `/` when there is a potential conflict but I understand it might not be as simple as It sounds :) 

In any case, keep up the good work; your extension is pretty awesome!
