### ISSUE TITLE
Ignore specified characters when sorting

### ISSUE THREAD

**Issue by JordanLongstaff** [daidodo/tsimportsorter#19]
**Is your feature request related to a problem? Please describe.**
Hi, I found another case in my workspace that is a violation of what I wanted from #4.

```
import { ActivityGroup, ACTIVITY_CHART_TOTAL_DAYS, RootDashboardPageProvider } from "./";
```

It's supposed to look like this:
```
import { ACTIVITY_CHART_TOTAL_DAYS, ActivityGroup, RootDashboardPageProvider } from "./";
```

I'm guessing that it's the underscore that's causing the problem here because my `sortRules` is:
```
"sortRules": {
    "names": ["Aa"]
}
```

**Describe the solution you'd like**
It's probably worth it to allow the user to specify what characters, strings or regular expressions should be ignored when determining how to sort imports.

**Describe alternatives you've considered**
Are there any alternatives? If so, I'd like to know what they are.

**Additional context**

**Comment by daidodo** [comment]
@JordanLongstaff thanks for your feedback!

Maybe you should set the rule as ["_", "Aa"].

I don't think we should ignore any chars because it causes more issues, e.g. what's the order of a_b and ab?

**Comment by JordanLongstaff** [comment]
Well, your suggestion fixed my issue, so I think I can drop this.

**Comment by JordanLongstaff** [comment]
Well, your suggestion fixed the issue, so I think I can drop this. Thanks!
