### ISSUE TITLE
Imports sorted on line lengths equal to maximum

### ISSUE THREAD

**Issue by JordanLongstaff** [daidodo/tsimportsorter#2]
The import sorter should allow import lines that are as long as the maximum and only wrap lines that are strictly longer, but instead it also wraps lines as long as the maximum. The workaround is to set the `maximumLineLength` to be one higher than the actual intended maximum length, which is confusing.

**Comment by daidodo** [comment]
Hi, thanks for using JS/TS Import Sorter. Will fix this soon!

**Comment by daidodo** [comment]
Fixed in v1.1.1.

**Comment by JordanLongstaff** [comment]
Thanks!
