### ISSUE TITLE
Option to allow for only sorting

### ISSUE THREAD

**Issue by roypearce** [daidodo/tsimportsorter#36]
In my projects, prettier controls line length and makes additional decisions about when to break the binding names onto multiple lines. Even with the following which gets it right most of the time to match prettier
```
{
  "maxBindingNamesPerLine": 0,
  "maxDefaultAndBindingNamesPerLine": 0
}
```
there are situations where there is a conflict between the `maxLineLength` from this project and prettier. For example the following import remains as one line with prettier despite breaking the line length rule because of the long import path, prettier decides to not break it up, but this plugin will force it onto 3 lines:
```
import { FakeImportWithVeryLooongName } from './components/fake-import-file-name-very-loooong/fake-import-file-name-very-loooong';
```

Since I want my projects to autofix to prettier rules, there will always be another change in this situation (you can see during on save, prettier fixes it to one line and then this plugin will force it to 3 immediately afterwards) and it will violate the prettier check in CI, and require the prettier fix to be done on the command line to make it match and pass the prettier check in CI.

Ideally the option would enforce formatting only to the specs of the rules in eslint and leave the bindings per line options up to prettier. Is this possible?

**Comment by daidodo** [comment]
Hi @roypearce, you can add `maxLineLength: 0` in so the extension will ignore line length as well:

```json
{
  "maxBindingNamesPerLine": 0,
  "maxDefaultAndBindingNamesPerLine": 0,
  "maxLineLength": 0
}
```

Basically the extension considers both line length and count of names to decide line wrapping. And `0` tells it to not care about either.

Hope that helps you!

**Comment by daidodo** [comment]
Same as https://github.com/daidodo/tsimportsorter/issues/29.

**Comment by roypearce** [comment]
The problem with adding the `maxLineLength` is that since this plugin applies the formatting after prettier runs, every import is now one-lined which further diverges the formatting from what prettier is doing. Having the same line lengths in prettier and this plugin gets it close but in the example I specified the logic differs, and prettiers formatting style should win out.

**Comment by daidodo** [comment]
I guess what you want is that the extension formats imports/exports first, and then prettier format the whole file?

If yes, you could install prettier AFTER this extension in VSCode, e.g. uninstall prettier and then install again. (I'm not sure how to specify formatter orders in VSCode but did once enter the situation that prettier ran after this extension.)

**Comment by Nxt3** [comment]
I tried installing them in a different order and it doesn't seem to have worked for me. Being able to disable all formatting and just handle grouping/sorting would be an amazing addition.
