### ISSUE TITLE
Option for case considerations when sorting imports

### ISSUE THREAD

**Issue by JordanLongstaff** [daidodo/tsimportsorter#4]
It is possible for bindings to have names with the same spelling apart from their cases. By default, the import sorter puts the lowercase one first:

```
import { a, A, b, B } from "/some/code/path";
```

I want an option to make uppercase imports come first:

```
import { A, a, B, b } from "/some/code/path";
```

**Comment by daidodo** [comment]
Hi @JordanLongstaff,

Sorry for the late response!
This issue has been resolved in v1.2.2.

Now you can config sorting rules for imported names, e.g.:

```json
"sortRules": { "names": ["_", "Aa"] }
```

which will:
* Put `'_'` (underscore) in front of letters `[a-zA-Z]`, and
* Compare letters *case-insensitively*, and upper-case letters are in front of lower-case letters.

[A wiki](https://github.com/daidodo/tsimportsorter/wiki/Sorting-Rules) with more details is on the way.
Please tell me if you have more questions!
Thanks!

**Comment by JordanLongstaff** [comment]
Thanks so much for these improvements! This is going to be a huge help.

**Comment by JordanLongstaff** [comment]
Actually, this isn't quite what I wanted. What's happening now is that every uppercase import is being placed in front of every lowercase import. I want imports to be compared case-insensitively with ties going to the uppercase import, as in my example.

**Comment by JordanLongstaff** [comment]
FYI my current sorting rule is `"sortRules": { "names": ["Aa"] }`, in case I'm just doing something wrong.

**Comment by JordanLongstaff** [comment]
Actually, maybe I should clarify my example a bit more. This might be very tricky, but what I see is:

```
import { aa, ab, Aa, Ab } from "some/code/path";
```

And what I want is:

```
import { Aa, aa, Ab, ab } from "some/code/path";
```

**Comment by JordanLongstaff** [comment]
Before version 1.2.2 they would have been sorted like this:

```
import { aa, Aa, ab, Ab } from "some/code/path";
```

**Comment by daidodo** [comment]
Thanks for your feedback!
I agree it's very tricky here. I'll try to fix it soon.

**Comment by daidodo** [comment]
Please try v1.2.3.

**Comment by JordanLongstaff** [comment]
Works perfectly now. Thanks a lot! (I used v1.2.4, actually.)
