### ISSUE TITLE
Single quote import path

### ISSUE THREAD

**Issue by aldd-waguirreo** [daidodo/tsimportsorter#40]
Suppor por single quote path

**Comment by daidodo** [comment]
Thanks for your feedback, @aldd-waguirreo!

Have you tried [quoteMark](https://github.com/daidodo/format-imports/blob/main/docs/interfaces/configuration.md#quotemark) option? You set it in *import-sorter.json* or *package.json* under `importSorter` section.

Examples:

*import-sorter.json:*
```json
{
  "quoteMark": "single"
}
```

Or

*package.json:*
```json
{
  "importSorter": {
    "quoteMark": "single"
  }
}
```
