### ISSUE TITLE
Support Type-Only imports in group rules

### ISSUE THREAD

**Issue by miZyind** [daidodo/tsimportsorter#42]
**Is your feature request related to a problem? Please describe.**
I can not find a correct setting to sort all the Type-Only import statements to the last group.

**Describe the solution you'd like**
It would be very helpful for me if I can define the following rules:
`"tsImportSorter.configuration.groupRules": [{}, "^[@]", "^[#]", "^[.]", "Type-Only"]`

**Additional context**
This is an example of the original sort result (with groupRules: `[{}, "^[@]", "^[#]", "^[.]"]`):
```typescript
import type {
  CognitoIdToken,
  CognitoUserSession,
} from 'amazon-cognito-identity-js';
import {
  AuthenticationDetails,
  CognitoUser,
  CognitoUserPool,
} from 'amazon-cognito-identity-js';

import {
  BadRequestException,
  Inject,
  Injectable,
  Logger,
} from '@nestjs/common';

import { AuthError } from './auth.constant';
import type { LogInDTO } from './dtos/log-in.dto';
```

This is what I prefer (with groupRules: `[{}, "^[@]", "^[#]", "^[.]", "Type-Only"]`):
```typescript
import {
  AuthenticationDetails,
  CognitoUser,
  CognitoUserPool,
} from 'amazon-cognito-identity-js';

import {
  BadRequestException,
  Inject,
  Injectable,
  Logger,
} from '@nestjs/common';

import Config, { AWSConfig } from '#configs';

import { AuthError } from './auth.constant';

import type {
  CognitoIdToken,
  CognitoUserSession,
} from 'amazon-cognito-identity-js';
import type { CognitoUserJWTPayload } from 'nestjs-xion/model';
import type { LogInDTO } from './dtos/log-in.dto';
```

**Comment by daidodo** [comment]
Hi @miZyind, thanks for the feedback!

This is a good suggestion and I'll see what I can do here!

**Comment by daidodo** [comment]
### Solution

A straightforward way is to add `importType: boolean` into [groupRule](https://github.com/daidodo/format-imports/blob/main/docs/interfaces/grouprule.md):

* When it's _true_, the group accepts only `import type`.
* When it's _false_, the group accepts only `import`.
* When it's _undefined/null_, the group accepts both.

So the above use case would be like this:
```json
"groupRules": [
  {"importType": false},
  {"regex": "^[@]", "importType": false},
  {"regex": "^[#]", "importType": false},
  {"regex": "^[.]", "importType": false},
]
```

**Explained:**
The matching happens in the same order of groups defined in `groupRules`. So you have to EXCLUDE `import type` from the groups before your "Type-Only" group.
Since the "Type-Only" group is the last and all other `import`s have been sorted, you don't need to explicitly define it in the `groupRules` because it's a [fall-back group](https://github.com/daidodo/format-imports/wiki/Grouping-Rules#fall-back-group).

#### Merge

When [mergeConfig](https://github.com/daidodo/format-imports/tree/main/docs#mergeconfig), `importType` will be overwritten.

#### Inheritance

Sub-groups don't need to inherit `importType` from the parent because imports have been filtered already.

@miZyind, please tell me your thoughts.
Thanks!

**Comment by miZyind** [comment]
@daidodo Thanks for your very quick reply! I have no other ideas because the solution you provided is much better than I expected 😄

**Comment by Torhal** [comment]
Using this method, how would the import types be sorted at the end? Not at all? The same as the defined groups?

**Comment by daidodo** [comment]
Hi @Torhal, what do you mean?

In @miZyind's example, all `import type`s are at the end, by falling into the fall-back group.

If you mean to place a defined type-only group at the end, you can do this:

```ts
"groupRules": [
  {},    // Fall-back group
  {"regex": "^a", "importType": true}  // The last type-only group
]
```

The key is to plan where the fall-back group is.
Hope that helps!

**Comment by daidodo** [comment]
@miZyind, I've release v7.2.0 which includes the feature above.
Please check it out and tell me if you have any questions.
Thanks!

**Comment by Torhal** [comment]
> If you mean to place a defined type-only group at the end, you can do this:
> 
> ```ts
> "groupRules": [
>   {},    // Fall-back group
>   {"regex": "^a", "importType": true}  // The last type-only group
> ]
> ```

What if I wanted a type-only group at the end, but also wanted them sorted the same way as non-type groups?

```ts
        "groupRules": [
            {},
            "^[@]",
            "^[~]",
            "^[.]"
        ],
```
Then, after that, have identical sorting as above but for the type-only imports.

**Comment by daidodo** [comment]
I see.
If you want type-only imports are in different groups (separated by an empty line), you can define those groups separately, e.g.:

```json
"groupRules": [
  {},
  "^[@]",
  "^[~]",
  "^[.]",
  {"importType": true},
  {"regex": "^[@]", "importType": true},
  {"regex": "^[~]", "importType": true},
  {"regex": "^[.]", "importType": true}
],
```

If you want type-only imports are in one group (no empty lines in between) but sorted the same way, you can use sub-groups:

```json
"groupRules": [
  {},
  "^[@]",
  "^[~]",
  "^[.]",
  {"importType": true, "subGroups": [{}, "^[@]", "^[~]", "^[.]"]},
],
```

You can also check out [Grouping Rules](https://github.com/daidodo/format-imports/wiki/Grouping-Rules) wiki for more info.

**Comment by Torhal** [comment]
Ah, good deal! Thank you!

**Comment by miZyind** [comment]
@daidodo I've given it a try. It looks awesome 👍
Let me share my config and test result here.

This is the current `groupRule` I defined:
```json
[
  { "importType": false },
  { "regex": "^[@]", "importType": false },
  { "regex": "^[#]", "importType": false },
  { "regex": "^[.]", "importType": false },
  [{}, "^[@]", "^[#]", "^[.]"]
]
```
1. I would like to sort the **non-type** `fall-back group` on the top.
2. Sort the **non-type** `regex groups` in the middle.
3. Sort others **type** groups at the end and follow the order of **pre-defined** `regex groups (@ -> # -> .)`.

This is the sort result of 7.1.0 `with groupRules: [{}, "^[@]", "^[#]", "^[.]"]`:
```typescript
import type { FindOneOptions } from 'typeorm';
import { In, Like, Not, QueryFailedError, Repository } from 'typeorm';

import { BadRequestException, Injectable } from '@nestjs/common';
import { InjectRepository } from '@nestjs/typeorm';
import { TypeOrmCrudService } from '@nestjsx/crud-typeorm';

import { Category } from '#entities/category.entity';
import type { LanguageConfig } from '#modules/language/language.config';
import { LanguageService } from '#modules/language/language.service';

import { CreateCategoryDTO } from './dtos/create-category.dto';
```

This is the sort result of 7.2.0:
```typescript
import { In, Like, Not, QueryFailedError, Repository } from 'typeorm';

import { BadRequestException, Injectable } from '@nestjs/common';
import { InjectRepository } from '@nestjs/typeorm';
import { TypeOrmCrudService } from '@nestjsx/crud-typeorm';

import { Category } from '#entities/category.entity';
import { LanguageService } from '#modules/language/language.service';

import { CreateCategoryDTO } from './dtos/create-category.dto';

import type { FindOneOptions } from 'typeorm';
import type { LanguageConfig } from '#modules/language/language.config';
```

Thank you very much for your support 😄
I think that the issue has been solved  🎉🎉
