### ISSUE TITLE
Missing Option to turn of blank line after group

### ISSUE THREAD

**Issue by Elias-Graf** [daidodo/tsimportsorter#6]
> Feature Request

I don't mind the grouping but I did not see any option to disable the empty
line after each group.

**Comment by daidodo** [comment]
Thanks for your feedback!

One way to "turn off" the blank line is moving groups to **subgroups**. E.g.

```json
"groupRules": [[{}, "^[@]", "^[.]"]]
```

Now there is no empty lines between imports but still they are *sub-grouped*.

```ts
import A from 'some_module';
import B from '@alias_module';
import C from './relative_module';
```

Is that what you want?

**Comment by Elias-Graf** [comment]
I've read about that in the docs. It said something like: "subgroups do not have a blank like". You may want to describe this more explicitly. 

(may I ask another question here, or do you not want this for organization purposes?)

**Comment by daidodo** [comment]
Feel free to ask questions here or open new issues if you want.

Sorry for the ambiguity in the wiki but I'm not sure how to improve since I'm not English-native. So it'd be great if you can help. ;P

Regarding the new option, I can see where you come from but I don't feel a strong need as there are different ways to think of it, e.g. groups vs. subgroups. But I'll keep it in the TODOs and give it more time to show up.

Hope that helps!

**Comment by Elias-Graf** [comment]
Oh don't worry about your language, it's totally fine and btw, neither am I a native speaker.

## About subgroups

I imagined subgroups being sort-groups inside sort-groups. And my train of thought was: "No, sub-groups is not what I want, I want to keep `normal` groups". But if it is your recommendation to use sub-groups instead of "major" groups you should explicitly state:

> To remove spacing between groups, move your groups to subgroups, and here is how: <...>.

## Additional request

I know this is a import-sorter, but in our project, there are a lot of re-exports. An example of it would be: 

````
export {
	Foo,
	Foo2
	Foo3
} from './foo';
export {Bar, Bar} from './bar';
export {
	Wood1
	Wood2
	Wood3
	Wood4
	Wood5
	Wood6
	Wood7
} from './log';
````

Do you think it would be possible to also sort those?

Cheers :)

**Comment by daidodo** [comment]
Thanks for the clarification for sub-groups!

Sorting exports is quite a feature in my TODO list. I will do some estimation first and come back to you.

**Comment by daidodo** [comment]
Interestingly, all the following are valid export statements:

```ts
export let a: boolean, b: number; // const, var
export const c = 10, d = 'abc';   // let, var

let i = { j: 10, k: 'x' };
export const { j, k: l } = i; // let, var

export function e() { return 2; }
export function* ee() { return 2; }

export type A = string;
export interface B { }
export class B { }

export default c > 10
export default a = false
export default function () { }
export default function m() { }
export default interface C { }
export default class D { }
const f = 1, g = true;
export { i as default, f, g as h }

export * from './hi'  // defualt export is excluded
export * as n from './hi'

export { default, default as dd, aa, bb as cc } from './hi'
export { aa as default, default as dd, aa, bb as cc } from './hi'
```

### Feature definitions
Among those, the following 3 examples are sortable by the plugin:

``` ts
export { i as default, f, g as h }
export { default, default as dd, aa, bb as cc } from './hi'
export { aa as default, default as dd, aa, bb as cc } from './hi'
```

#### 1. Should we rearrange exports by, e.g. module paths or binding names?
No. This is an uncharted area for now. But suggestions and info would be appreciated.

#### 2. Should we merge exports?
* Case 1: Yes.
```ts
export { A as default, default as B, C } from 'm'
export { D } from 'm'
```
=>
```ts
export { A as default, default as B, C, D } from 'm'
```
* Case 2: No.
```ts
export default A
export { B, C }
```
!=>
```ts
export { A as default, B, C }
```

#### 3. Should we merge comments?
* Case 1: Yes.
```ts
export { A, B }
export { C }  // comment
```
=>
```ts
export { A, B, C }  // comment
```
* Case 2: No.
```ts
export { A, B }  // comment 1
export { C }     // comment 2
```

Please tell me your thoughts and if that's what you need!
Thanks!

**Comment by daidodo** [comment]
Exported binding names are sorted using the existing rules, i.e.:
* `'default'` < any other strings
* In case of `aliasName as propName`, compare `aliasName` first and then `propName`
* Strings are compared via `"sortRules.names"` settings.

**Comment by daidodo** [comment]
@Elias-Graf, formatting exports is released in v2.0.0. Please have a try and tell me if you have any questions.

Thanks!

**Comment by Elias-Graf** [comment]
# Feedback Definitions
I agree with every feature definition except case 1 of point 3.

> 3. Should we merge comments?
Case 1: Yes.
export { A, B }
export { C }  // comment

The comment could be (it probably **will** be) specific to `C` and could be confusing, misleading and-/or is unclear to which symbol it refers to if it is merged. Especially because the comment is placed on the line with `C` and so `C` will likely not be directly mentioned inside the comment.

# Feedback using it
The sorter seems to be sorting just fine! really well done!

Though I have one question: in `export default` it looks like every export is staying on a single line. This might very well be an oversight on my part so excuse me if that's the case.

Here's my config:
```
{
	"autoFormat": "onSave",
	"bracketSpacing": false,
	"groupRules": [[{}, "^[@]", "^[.]"]],
	"maxBindingNamesPerLine": 0,
	"maxDefaultAndBindingNamesPerLine": 0,
	"maxExportNamesPerLine": 0,
	"maxLineLength": 100,
	"maxNamesPerWrappedLine": 0,
	"quoteMark": "single",
	"tabType": "tab"
}

```

Have a nice day ^^

**Comment by daidodo** [comment]
@Elias-Graf, thanks for your feedback!

This plugin doesn’t format `export default { }` because it’s a syntax error.

Regarding the merge comment case, I’d like to see more real world examples.

I’ll close this issue but feel free to open a new one if you have any questions!

**Comment by daidodo** [comment]
The first issue is resolved in https://github.com/daidodo/tsimportsorter/issues/3.
